import { Router } from 'express';
import { authRoutes } from '../features/auth';
import { emailVerificationRoutes } from '../features/emailVerification';
import { referralRoutes } from '../features/referral';
import { heroImageRoutes } from '../features/home';
import { timeDealRoutes } from '../features/timeDeal';
import { bestProductRoutes } from '../features/bestProduct';
import { middleBannerRoutes } from '../features/middleBanner';
import { freshFoodRoutes } from '../features/freshFood';
import { mdPickRoutes } from '../features/mdPick';
import { badameunRoutes } from '../features/badameun';
import { bongseonjangTvRoutes } from '../features/bongseonjangTv';
import { bongcookRoutes } from '../features/bongcook';
import { bottomBannerRoutes } from '../features/bottomBanner';
import { productRoutes } from '../features/product';
import { eventRoutes } from '../features/event';
import { reviewRoutes } from '../features/review';
import { searchRoutes } from '../features/search';
import { profileRoutes } from '../features/profile';
import { pointRoutes } from '../features/point';
import { cartRoutes } from '../features/cart';
import { couponRoutes } from '../features/coupon';
import { wishlistRoutes } from '../features/wishlist';

const router = Router();

router.use('/auth', authRoutes);
router.use('/email-verification', emailVerificationRoutes);
router.use('/referral', referralRoutes);
router.use('/home', heroImageRoutes);
router.use('/time-deals', timeDealRoutes);
router.use('/best-products', bestProductRoutes);
router.use('/middle-banners', middleBannerRoutes);
router.use('/fresh-foods', freshFoodRoutes);
router.use('/md-picks', mdPickRoutes);
router.use('/badameun', badameunRoutes);
router.use('/bongseonjang-tv', bongseonjangTvRoutes);
router.use('/bongcook', bongcookRoutes);
router.use('/bottom-banners', bottomBannerRoutes);
router.use('/products', productRoutes);
router.use('/events', eventRoutes);
router.use('/reviews', reviewRoutes);
router.use('/search', searchRoutes);
router.use('/profile', profileRoutes);
router.use('/points', pointRoutes);
router.use('/cart', cartRoutes);
router.use('/coupons', couponRoutes);
router.use('/wishlist', wishlistRoutes);

export default router;
