import { Router } from 'express';
import { authRoutes, passwordResetRoutes } from '../features/auth';
import { emailVerificationRoutes } from '../features/emailVerification';
import { referralRoutes } from '../features/referral';
import { bestProductRoutes } from '../features/bestProduct';
import { bongseonjangTvRoutes } from '../features/bongseonjangTv';
import { productRoutes } from '../features/product';
import { eventRoutes } from '../features/event';
import { reviewRoutes } from '../features/review';
import { searchRoutes } from '../features/search';
import { profileRoutes } from '../features/profile';
import { pointRoutes } from '../features/point';
import { cartRoutes } from '../features/cart';
import { couponRoutes, adminCouponRoutes } from '../features/coupon';
import { wishlistRoutes } from '../features/wishlist';
import { orderHistoryRoutes } from '../features/orderHistory';
import { paymentRoutes } from '../features/payment/routes/paymentRoutes';
import { addressRoutes } from '../features/address';
import { uploadRoutes } from '../features/upload';
import { noticeRoutes, publicNoticeRoutes } from '../features/notice';
import { investmentInfoRoutes, publicInvestmentInfoRoutes } from '../features/investmentInfo';
import { faqRoutes, publicFaqRoutes } from '../features/faq';
import { inquiryRoutes } from '../features/inquiry';
import { adminBannerRoutes, publicHeroRoutes, publicMiddleBannerRoutes, publicBottomBannerRoutes, publicMypageBannerRoutes } from '../features/banner';
import { adminProductRoutes } from '../features/admin/routes/adminProductRoutes';
import { adminUserRoutes } from '../features/admin/routes/adminUserRoutes';
import { adminOrderRoutes } from '../features/admin/routes/adminOrderRoutes';
import { userRoutes } from '../features/user';
import { termsRoutes, adminTermsRoutes } from '../features/terms';
import homeDataRoutes from '../features/home/routes/homeDataRoutes';
import { adminAuthMiddleware } from '../common/middleware/adminAuthMiddleware';

const router = Router();
const adminRouter = Router();
adminRouter.use(adminAuthMiddleware);

router.use('/auth', authRoutes);
router.use('/auth/password-reset', passwordResetRoutes);
router.use('/email-verification', emailVerificationRoutes);
router.use('/referral', referralRoutes);
router.use('/home', homeDataRoutes);
router.use('/home', publicHeroRoutes);
router.use('/middle-banners', publicMiddleBannerRoutes);
router.use('/bottom-banners', publicBottomBannerRoutes);
router.use('/mypage-banners', publicMypageBannerRoutes);
router.use('/best-products', bestProductRoutes);
router.use('/bongseonjang-tv', bongseonjangTvRoutes);
router.use('/products', productRoutes);
router.use('/events', eventRoutes);
router.use('/reviews', reviewRoutes);
router.use('/search', searchRoutes);
router.use('/profile', profileRoutes);
router.use('/users', userRoutes);
router.use('/points', pointRoutes);
router.use('/cart', cartRoutes);
router.use('/coupons', couponRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/orders', orderHistoryRoutes);
router.use('/payment', paymentRoutes);
router.use('/address', addressRoutes);
router.use('/upload', uploadRoutes);
router.use('/terms', termsRoutes);
router.use('/faqs', publicFaqRoutes);
router.use('/notices', publicNoticeRoutes);
router.use('/investment-infos', publicInvestmentInfoRoutes);
adminRouter.use('/notices', noticeRoutes);
adminRouter.use('/investment-infos', investmentInfoRoutes);
adminRouter.use('/faqs', faqRoutes);
adminRouter.use('/inquiries', inquiryRoutes);
adminRouter.use('/', adminBannerRoutes);
adminRouter.use('/', adminCouponRoutes);
adminRouter.use('/products', adminProductRoutes);
adminRouter.use('/users', adminUserRoutes);
adminRouter.use('/orders', adminOrderRoutes);
adminRouter.use('/terms', adminTermsRoutes);

router.use('/admin', adminRouter);

export default router;
