import { Router } from 'express';
import { authRoutes } from '../features/auth';
import { emailVerificationRoutes } from '../features/emailVerification';
import { referralRoutes } from '../features/referral';
import { bestProductRoutes } from '../features/bestProduct';
import { bongseonjangTvRoutes } from '../features/bongseonjangTv';
import { productRoutes } from '../features/product';
import { eventRoutes } from '../features/event';
import { reviewRoutes } from '../features/review';
import { searchRoutes } from '../features/search';
import { profileRoutes } from '../features/profile';
import { pointRoutes } from '../features/point';
import { cartRoutes } from '../features/cart';
import { couponRoutes, adminCouponRoutes } from '../features/coupon';
import { wishlistRoutes } from '../features/wishlist';
import { orderHistoryRoutes } from '../features/orderHistory';
import { paymentRoutes } from '../features/payment/routes/paymentRoutes';
import { addressRoutes } from '../features/address';
import { uploadRoutes } from '../features/upload';
import { noticeRoutes } from '../features/notice';
import { faqRoutes } from '../features/faq';
import { inquiryRoutes } from '../features/inquiry';
import { adminBannerRoutes, publicHeroRoutes, publicMiddleBannerRoutes, publicBottomBannerRoutes } from '../features/banner';
import { adminProductRoutes } from '../features/admin/routes/adminProductRoutes';
import { adminUserRoutes } from '../features/admin/routes/adminUserRoutes';
import { adminOrderRoutes } from '../features/admin/routes/adminOrderRoutes';
import { userRoutes } from '../features/user';
import { termsRoutes, adminTermsRoutes } from '../features/terms';

const router = Router();

router.use('/auth', authRoutes);
router.use('/email-verification', emailVerificationRoutes);
router.use('/referral', referralRoutes);
router.use('/home', publicHeroRoutes);
router.use('/middle-banners', publicMiddleBannerRoutes);
router.use('/bottom-banners', publicBottomBannerRoutes);
router.use('/best-products', bestProductRoutes);
router.use('/bongseonjang-tv', bongseonjangTvRoutes);
router.use('/products', productRoutes);
router.use('/events', eventRoutes);
router.use('/reviews', reviewRoutes);
router.use('/search', searchRoutes);
router.use('/profile', profileRoutes);
router.use('/users', userRoutes);
router.use('/points', pointRoutes);
router.use('/cart', cartRoutes);
router.use('/coupons', couponRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/orders', orderHistoryRoutes);
router.use('/payment', paymentRoutes);
router.use('/address', addressRoutes);
router.use('/upload', uploadRoutes);
router.use('/terms', termsRoutes);
router.use('/admin/notices', noticeRoutes);
router.use('/admin/faqs', faqRoutes);
router.use('/admin/inquiries', inquiryRoutes);
router.use('/admin', adminBannerRoutes);
router.use('/admin', adminCouponRoutes);
router.use('/admin/products', adminProductRoutes);
router.use('/admin/users', adminUserRoutes);
router.use('/admin/orders', adminOrderRoutes);
router.use('/admin/terms', adminTermsRoutes);

export default router;
